%% ========================================================================
% MASTER CINEMATIC DRONE TRACKER & TELEMETRY EXPORTER
% Architecture: High-Fidelity 2D Spatial Visualization
% Features: Photorealistic Terrazzo Rendering, Dynamic Tire Steering, 
% Obstacle Overlays, and Live Analog Speedometer HUD.
% Purpose: Translates raw mathematical telemetry into an intuitive, 
% stakeholder-ready visual format. Proves the real-world spatial 
% effectiveness of the controller's trajectory management.
% =========================================================================
clc; close all; clear v; 

fprintf('Initializing Cinematic Drone Tracker...\n');

% =========================================================================
% 1. DATA EXTRACTION & KINEMATIC SYNTHESIS
% =========================================================================
% Dynamically hooks into either the active base workspace or the 'out' 
% object generated by the MBD master simulation script.
try
    ideal_path = evalin('base', 'path_waypoints');
    
    if exist('out', 'var')
        x_data = out.Actual_X.Data;
        y_data = out.Actual_Y.Data;
        yaw_data = out.Actual_Yaw.Data; 
        steer_data = out.Steering_Angle.Data;
        time_data = out.tout;
    else
        x_data = evalin('base', 'Actual_X.Data');
        y_data = evalin('base', 'Actual_Y.Data');
        yaw_data = evalin('base', 'Actual_Yaw.Data');
        steer_data = evalin('base', 'Steering_Angle.Data');
        time_data = evalin('base', 'tout');
    end
catch ME
    error('Extraction Failed. Ensure Actual_Yaw and Steering_Angle are exported to the workspace.');
end

% --- PRE-CALCULATE LIVE SPEEDS (km/h) ---
% Derives velocity explicitly from positional differentials to perfectly 
% sync with the variable-step solver timeline.
num_frames = length(time_data);
speed_kmh = zeros(num_frames, 1);
for i = 2:num_frames
    dx = x_data(i) - x_data(i-1);
    dy = y_data(i) - y_data(i-1);
    dt = time_data(i) - time_data(i-1);
    if dt > 0
        speed_kmh(i) = (sqrt(dx^2 + dy^2) / dt) * 3.6;
    else
        speed_kmh(i) = speed_kmh(i-1);
    end
end
if num_frames > 1
    speed_kmh(1) = speed_kmh(2); 
end
% ---------------------------------------------------------

% =========================================================================
% 2. AUTO-DETECT MODEL IDENTIFIER FOR RENDER TITLE
% =========================================================================
valid_models = {'M01', 'M02', 'M03', 'M04', 'M05'};
model_input = input('Enter the last run model number (M01 to M05): ', 's');
model_input = strtrim(upper(model_input));

if ~ismember(model_input, valid_models)
    error('Invalid model number "%s". Please enter one of: M01, M02, M03, M04, M05.', model_input);
end
plot_title = sprintf('%s: Real-Time Telemetry & Dynamics', model_input);

% =========================================================================
% 3. DIRECTORY ROUTING & VIDEO ENCODER SETUP
% =========================================================================
user_filename = input('Enter a name to save this video (or press Enter to use default "CinematicDrone"): ', 's');
if isempty(user_filename), user_filename = 'CinematicDrone'; end
if ~endsWith(user_filename, '.mp4'), user_filename = [user_filename, '.mp4']; end

% Map standard project directories for clean repository structure
script_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(script_dir);
data_dir = fullfile(project_dir, 'data');
res_dir = fullfile(project_dir, 'resources'); 

if ~exist(data_dir, 'dir'), mkdir(data_dir); end
video_filepath = fullfile(data_dir, user_filename);

v = VideoWriter(video_filepath, 'MPEG-4');
v.FrameRate = 30; v.Quality = 100;
open(v);

% =========================================================================
% 4. ENVIRONMENT: TERRAZZO FLOOR & ASPHALT GENERATION
% =========================================================================
fig = figure('Name', 'Cinematic Tracker', 'Color', [0.05 0.05 0.05], 'Position', [100, 100, 900, 800]);
ax = axes('Parent', fig, 'Color', [0.05 0.05 0.05]); 
hold(ax, 'on'); grid(ax, 'on'); axis(ax, 'equal');

% High-contrast gridlines for spatial reference
ax.GridColor = [0.980 0.275 0.086]; 
ax.GridAlpha = 0.7; 
ax.LineWidth = 1.5; 
ax.XColor = 'w'; ax.YColor = 'w';
xlabel(ax, 'Global X (m)'); ylabel(ax, 'Global Y (m)');
title(ax, plot_title, 'FontSize', 14, 'FontWeight', 'bold', 'Color', 'w');

% --- THE TERRAZZO SPECKLE ENGINE (Optical Flow Generator) ---
% Generates a randomized field of high-contrast specks. This is critical for 
% visualizing high-speed longitudinal and lateral translation (slip) that is 
% otherwise imperceptible on solid color surfaces.
fprintf('Generating Dense Terrazzo Floor...\n');
min_x = min(ideal_path(:,1)) - 8; max_x = max(ideal_path(:,1)) + 8;
min_y = min(ideal_path(:,2)) - 8; max_y = max(ideal_path(:,2)) + 8;

% >>> RENDER CONFIGURATION: Terrazzo Density and Size
num_specks = 800000; % Increase for denser optical flow
speck_size_multiplier = 6; % Increase for larger specks

rx = min_x + rand(num_specks, 1) * (max_x - min_x);
ry = min_y + rand(num_specks, 1) * (max_y - min_y);
rs = rand(num_specks, 1) * speck_size_multiplier + 1; 

c_opts = [1 1 1; 0.980 0.275 0.086; 0.05 0.05 0.05; 0.980 0.400 0.200; 0.7 0.7 0.7]; 
c_idx = randi(size(c_opts,1), num_specks, 1);
c = c_opts(c_idx, :);
scatter(ax, rx, ry, rs, c, 'filled', 'MarkerFaceAlpha', 0.8);

% --- ASPHALT TRACK GENERATION ---
% >>> RENDER CONFIGURATION: Track Bounds
track_width = 1.4; % Modify width of the rendered black asphalt

nx = zeros(size(ideal_path,1), 1); ny = zeros(size(ideal_path,1), 1);
for k = 1:size(ideal_path,1)-1
    dx = ideal_path(k+1,1) - ideal_path(k,1); dy = ideal_path(k+1,2) - ideal_path(k,2);
    L_norm = sqrt(dx^2 + dy^2);
    nx(k) = -dy/L_norm; ny(k) = dx/L_norm;
end
nx(end) = nx(end-1); ny(end) = ny(end-1);

left_bound = ideal_path + [nx, ny] * (track_width/2);
right_bound = ideal_path - [nx, ny] * (track_width/2);
track_x = [left_bound(:,1); flipud(right_bound(:,1))];
track_y = [left_bound(:,2); flipud(right_bound(:,2))];

% Draw the Asphalt (Z=0) and Centerline
fill(ax, track_x, track_y, [0.15 0.15 0.15], 'EdgeColor', [0 0 0], 'LineWidth', 2);
plot(ax, ideal_path(:,1), ideal_path(:,2), 'w--', 'LineWidth', 2);

% --- DYNAMIC MULTI-OBSTACLE VISUALIZATION (APF PROOF) ---
if evalin('base', 'exist(''enable_obstacle'', ''var'')') && evalin('base', 'enable_obstacle') == 1
    num_obs = evalin('base', 'num_obstacles');
    obs_x_val = evalin('base', 'obs_x'); obs_y_val = evalin('base', 'obs_y');
    plot(ax, obs_x_val(1:num_obs), obs_y_val(1:num_obs), 'rp', 'MarkerFaceColor', 'r', 'MarkerSize', 16, 'DisplayName', 'Stalled Vehicle(s)');
end

% --- ANALOG SPEEDOMETER HUD ---
hud_ymin = -0.3; % Space for the digital readout below
ax_hud = axes('Parent', fig, 'Position', [0.70 0.05 0.28 0.35]);
axis(ax_hud, 'equal'); axis(ax_hud, 'off'); hold(ax_hud, 'on');
fill(ax_hud, [-1.3 1.3 1.3 -1.3], [hud_ymin hud_ymin 1.25 1.25], [0.05 0.05 0.05], 'FaceAlpha', 0.8, 'EdgeColor', [0.980 0.275 0.086], 'LineWidth', 1.5);

% Draw Colored Analog Dial (Orange -> Light Orange -> White)
max_speed_kmh = 60;
theta_green = linspace(pi, pi - (30/max_speed_kmh)*pi, 50);
plot(ax_hud, cos(theta_green), sin(theta_green), 'Color', '#FA4616', 'LineWidth', 4);
theta_yellow = linspace(pi - (30/max_speed_kmh)*pi, pi - (45/max_speed_kmh)*pi, 50);
plot(ax_hud, cos(theta_yellow), sin(theta_yellow), 'Color', '#FC7A50', 'LineWidth', 4);
theta_red = linspace(pi - (45/max_speed_kmh)*pi, 0, 50);
plot(ax_hud, cos(theta_red), sin(theta_red), 'Color', '#FFFFFF', 'LineWidth', 4);

% Draw Ticks and Labels
for v_tick = 0:10:max_speed_kmh
    th = pi - (v_tick/max_speed_kmh)*pi;
    plot(ax_hud, [0.9*cos(th), cos(th)], [0.9*sin(th), sin(th)], 'w', 'LineWidth', 2);
    text(ax_hud, 0.75*cos(th), 0.75*sin(th), num2str(v_tick), 'Color', 'w', 'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
end
text(ax_hud, 0, 0.35, 'km/h', 'Color', 'w', 'FontSize', 12, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');

c_color = [0.980, 0.275, 0.086]; % Match trajectory color
h_needle = plot(ax_hud, [0, -0.85], [0, 0], '-', 'Color', c_color, 'LineWidth', 3); % Start at 0
text(ax_hud, -0.1, -0.15, 'TEST VEHICLE', 'Color', c_color, 'FontWeight', 'bold', 'FontSize', 10, 'HorizontalAlignment', 'right');
h_val_text = text(ax_hud, 0.1, -0.15, '0.0', 'Color', c_color, 'FontWeight', 'bold', 'FontSize', 12, 'HorizontalAlignment', 'left', 'FontName', 'Courier New');
plot(ax_hud, 0, 0, 'ko', 'MarkerFaceColor', [0.980 0.275 0.086], 'MarkerSize', 14); % Center Pin

% Trajectory Tail
tail_line = plot(ax, x_data(1), y_data(1), '-', 'Color', [0.980, 0.275, 0.086], 'LineWidth', 2.5);

% =========================================================================
% 5. VEHICLE HIERARCHY SETUP (Dynamics Visualization Mechanics)
% =========================================================================
% True physics distances used by the control algorithms
a_dist = 0.21; b_dist = 0.13; 
track_width_car = 0.18; 
w_l = 0.08; w_w = 0.035; 

% >>> RENDER CONFIGURATION: Front Wheel Alignment
% Shift front wheels visually relative to the chassis image
front_wheel_visual_offset = -0.03; 

car_hg = hgtransform('Parent', ax);

% --- BULLETPROOF TEXTURE MAPPING ---
% Maps a photorealistic chassis image onto a 3D surface. This prevents 
% the MATLAB renderer from stalling when translating high-res images.
img_path = fullfile(res_dir, 'rc_car.png'); 
if isfile(img_path)
    [img, ~, alpha] = imread(img_path);
    if isempty(alpha), alpha = ones(size(img,1), size(img,2)); end
    
    [X_img, Y_img] = meshgrid([-b_dist-0.08, a_dist+0.08], [track_width_car/2 + 0.05, -track_width_car/2 - 0.05]);
    Z_img = ones(size(X_img)) * 0.1; 
    
    h_img = surface(ax, X_img, Y_img, Z_img, img, 'FaceColor', 'texturemap', 'EdgeColor', 'none', 'Parent', car_hg);
    h_img.FaceAlpha = 'texturemap';
    h_img.AlphaData = alpha;
else
    % Fallback Geometric Chassis Vector
    c_l = a_dist + b_dist + 0.1; c_w = 0.16;
    fill(ax, [-b_dist-0.05, a_dist+0.05, a_dist+0.05, -b_dist-0.05], [-c_w/2, -c_w/2, c_w/2, c_w/2], [0.980 0.275 0.086], 'Parent', car_hg, 'EdgeColor', 'k');
    fill(ax, [0, a_dist-0.02, a_dist-0.02, 0], [-c_w/2.5, -c_w/3, c_w/3, c_w/2.5], [0 0 0], 'Parent', car_hg, 'EdgeColor', 'k');
    fill(ax, [-b_dist-0.06, -b_dist-0.01, -b_dist-0.01, -b_dist-0.06], [-c_w/1.8, -c_w/1.8, c_w/1.8, c_w/1.8], [0.980, 0.275, 0.086], 'Parent', car_hg, 'EdgeColor', 'k');
end

% --- INDEPENDENT STEERING WHEELS ---
% Rear Wheels (Fixed to chassis)
fill(ax, [-w_l/2, w_l/2, w_l/2, -w_l/2] - b_dist, [-w_w/2, -w_w/2, w_w/2, w_w/2] + track_width_car/2, [0 0 0], 'Parent', car_hg, 'EdgeColor', 'k'); 
fill(ax, [-w_l/2, w_l/2, w_l/2, -w_l/2] - b_dist, [-w_w/2, -w_w/2, w_w/2, w_w/2] - track_width_car/2, [0 0 0], 'Parent', car_hg, 'EdgeColor', 'k'); 

% Front Wheels (Independent pivot transformations)
fl_hg = hgtransform('Parent', car_hg); fr_hg = hgtransform('Parent', car_hg); 
fill(ax, [-w_l/2, w_l/2, w_l/2, -w_l/2], [-w_w/2, -w_w/2, w_w/2, w_w/2], [0 0 0], 'Parent', fl_hg, 'EdgeColor', 'k');
fill(ax, [-w_l/2, w_l/2, w_l/2, -w_l/2], [-w_w/2, -w_w/2, w_w/2, w_w/2], [0 0 0], 'Parent', fr_hg, 'EdgeColor', 'k');

view_padding = 2.5; 

% =========================================================================
% 6. ANIMATION LOOP (The Cinema Engine)
% =========================================================================
fprintf('Rendering Cinematic Video... Please do not close the figure.\n');
step_size = 3; 

try
    for i = 1:step_size:length(time_data)
        
        current_x = x_data(i); current_y = y_data(i);
        current_yaw = yaw_data(i); current_steer = steer_data(i);
        
        set(tail_line, 'XData', x_data(1:i), 'YData', y_data(1:i));
        
        % Move Chassis (Global Translation & Yaw)
        car_matrix = makehgtform('translate', [current_x, current_y, 0], 'zrotate', current_yaw);
        set(car_hg, 'Matrix', car_matrix);
        
        % Steer Wheels (Local rotation relative to chassis)
        fl_matrix = makehgtform('translate', [a_dist + front_wheel_visual_offset, track_width_car/2, 0], 'zrotate', current_steer);
        fr_matrix = makehgtform('translate', [a_dist + front_wheel_visual_offset, -track_width_car/2, 0], 'zrotate', current_steer);
        set(fl_hg, 'Matrix', fl_matrix); set(fr_hg, 'Matrix', fr_matrix);
        
        % --- UPDATE LIVE ANALOG SPEEDOMETER HUD ---
        if i >= length(time_data) - step_size
            set(h_val_text, 'String', 'STOPPED');
            set(h_needle, 'XData', [0, -0.85], 'YData', [0, 0]); % Drop needle
        else
            spd = speed_kmh(i);
            set(h_val_text, 'String', sprintf('%5.1f', spd));
            th = pi - (min(spd, max_speed_kmh)/max_speed_kmh)*pi; % Map speed to angle
            set(h_needle, 'XData', [0, 0.85*cos(th)], 'YData', [0, 0.85*sin(th)]);
        end
        % ------------------------------------------
        
        % Lock Camera (Drone Tracking)
        xlim(ax, [current_x - view_padding, current_x + view_padding]);
        ylim(ax, [current_y - view_padding, current_y + view_padding]);
        
        drawnow;
        writeVideo(v, getframe(fig));
    end
    
    close(v);
    fprintf('\nSuccess! Video saved to:\n%s\n', video_filepath);
    
catch ME
    close(v); 
    rethrow(ME);
end